travis:
  secure:
    BINSTAR_TOKEN: MkLq/agY8nrySgu0y4ONeM9uzzPXzZydm5dm8bQmIiBxXnmBlDslXQSaAqv3FXSVzYPXdmhN3y9ELLYQhN1/GUDVaMeIUARTylWurAiDW9ZFkojoYc8N7ZuQHocLtB7AdRMpcRU9+qjs0qc4NQHbhrLUYHwXdo+iZUG0sFutm0k0QewhgIwkEgC+0Np9uRe18QCUbAKn1LOvdweB4peXLDrvHtFB0kDlaPQBdrr3s4nuXcJDg9poRSmdDa6TXQcAL9dZ2eSIgZP0FvNSZ+RfaJwlfQOjQroW6mEXdHzti3hm05lRtvvobkcGjBjDOjHa7WnioAXTAfUR608KrCso07PoiytvOBjBTXozMqyR0WeQU3AkgqlmnutIjHwsNL0Ryxh3PxRhaht7Xosznxgy9np1i4MxxPfYZY/NrlLmSGuofa20qOg2k/3gnwljmm62eRR9dTE3Ok0UQV/jFjzZRv6rH7e5GzDi+9+4hRMQEQx9LO/RVfL+n/ucVnUHJHN5tyKknchNaQZEbT9wc5IlAeOFGAKAqPpvuZ2jFYk+418BKsF2YB0fnAhgyokOPzFnlH6ctyG248XKK7Lld5fUS0d540WseRf8lTn2xGEVl/Wt4JZNPUWnKrHl0fWD0za854jAu37a6REBT5KqC6P1s284PNxpOSuFm6zIp5gaDFE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
